tup = ()
vars_tup = ("Name", "Address", [1, 2, 3], ("ID", 3451))
book_tup = ("Python Programming")
book_tup1 = ("Python Programming",)
print (vars_tup)
print ("ชนิดข้อมูลของ vars_tup คือ", type(vars_tup))
print ("ชนิดข้อมูลของ book_tup คือ", type(book_tup))
print ("ชนิดข้อมูลของ book_tup1 คือ", type(book_tup1))