str1 = "Python"
str2 = "Python "
str3 = ""
str4 = " "
str5 = "อักขระหรือสตริง"
print ("จำนวนอักขระใน str1 =", len(str1))
print ("จำนวนอักขระใน str2 =", len(str2))
print ("จำนวนอักขระใน str3 =", len(str3))
print ("จำนวนอักขระใน str4 =", len(str4))
print ("จำนวนอักขระใน str5 =", len(str5))